plugins:
  plugin_name:
    executor: central_deployment_agent
    package_name: 'ENTER-PLUGIN-NAME-HERE'
    package_version: '1.0'

data_types:

  cloudify.datatypes.vsphere.Config:
    properties:
      username:
        description: >
          vSphere username.
        type: string
        required: false
      host:
        description: >
          vCenter hostname or IP address.
        type: string
        required: false
      password:
        description: >
          vCenter password.
        type: string
        required: false
      datacenter_name:
        description: >
          datacenter name.
        type: string
        required: false
      auto_placement:
        description: >
          Must be true if you are using clusters.
          Disabled `auto placement` is not recommended for a cluster.
          If `auto placement` set to false, plugin will provide recommendation
          to vsphere to place vm to selected host, vsphere can move vm to other
          host by internal logic.
        type: string
        required: false
      resource_pool_name:
        description: >
          Name of a resource pool.
          Defaults to Resources, which is a hidden resource pool on vSphere.
        type: string
        required: false
      port:
        description: >
          vCenter port for SDK.
        type: integer
        required: false
      allow_insecure:
        description: >
          Whether to allow insecure connections. Defaults to false, but this is not
          yet enforced on Python versions older than 2.7.9.
          Python versions pre-2.7.9 can only make insecure connections, which will
          fail in the next major version of this plugin unless this is set to false.
        type: boolean
        required: false
      certificate_path:
        description: >
          The path to the PEM encoded certificate for the vCenter. This will be used
          on Python 2.7.9 and above to verify the SSL connection.
          On older versions of python the connection will be insecure.
          It is not supported to set this while allow_insecure is set to 'true'.
        type: string
        required: false

node_types:

  cloudify.nodes.template.Test:
    derived_from: cloudify.nodes.Root
    properties:
      connection_config: 
        type: cloudify.datatypes.vsphere.Config
    interfaces:
      # you can define the lifecycle operation 
      # and whatever operation that you may need this node_type to support
      cloudify.interfaces.lifecycle:
        create:
          implementation: plugin_name.plugin.tasks.my_task